---
# Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: initialize.yml
- include_tasks: configure.yml
- meta: flush_handlers

#- name: Ensure PostgreSQL is started and enabled on boot.
#  service:
#    name: "{{ postgresql_daemon }}"
#    state: "{{ postgresql_service_state }}"
#    enabled: "{{ postgresql_service_enabled }}"

- include_tasks: data.yml
  when: postgres_new_data_dir is defined


# Configure PostgreSQL.
- import_tasks: users.yml
- import_tasks: databases.yml

