---
- name: restart postgresql
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_restarted_state }}"
    sleep: 5

#- name: make postgres restart
#  service:
#    name: "{{ postgresql_daemon }}"
#    state: "{{ postgresql_restarted_state }}"
#    sleep: 5
#  listen: "restart postgresql"

#- name: wait for 5 seconds
#  wait_for: timeout=5
#  delegate_to: localhost
#  listen: "restart postgresql"
